version: "3"

services:
  company:
    image: sabibm/company
    ports:
      - "9001:9001"
    networks:
      - micro
  agency:
    depends_on:
      - company
    image: sabibm/agency
    ports:
      - "9000:9000"
    networks:
      - micro
  edge-router:
    depends_on:
      - company
      - agency
    image: sabibm/edge-router
    ports:
      - "8080:8080"
    networks:
      - micro

networks:
  micro: