server:
  port: 8888

spring:
#  profiles: local
  config:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ibhi/config-data

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    preferIpAddress: true
